version: "3"

services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: always
    ports:
      - "61208:61208"
    pid: "host"
    environment:
      - "GLANCES_OPT=-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/dev:ro
