# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8081:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
    environment:
      TZ: "Europe/Berlin"
      FTLCONF_webserver_api_password: ${PIHOLE_WEB_UI_PASSWORD}
      FTLCONF_dns_listeningMode: "all"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - "./etc-pihole:/etc/pihole"
    restart: unless-stopped
