version: "3"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      - TZ=Europe/Berlin
      - WEBPASSWORD=admin
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80"
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped
