version: "3"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    network_mode: host
    ports:
      - 8080:80
    volumes:
      - ./config/conf.yml:/app/public/conf.yml:ro
